export const GL_RESIZE_TOPIC = "GL_RESIZE_TOPIC";
export const GL_TOUCH_MOVE_TOPIC = "GL_TOUCH_MOVE_TOPIC";
export const GL_TOUCH_END_TOPIC = "GL_TOUCH_END_TOPIC";
export const GL_TOUCH_START_TOPIC = "GL_TOUCH_START_TOPIC";
export const GL_TOUCH_HOLD_TOPIC = "GL_TOUCH_HOLD_TOPIC";
export const GL_WHEEL_TOPIC = "GL_WHEEL_TOPIC";
export const GL_KEYDOWN_TOPIC = "GL_KEYDOWN_TOPIC";
export const GL_KEYUP_TOPIC = "GL_KEYUP_TOPIC";
